//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class logsString
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string agent { get; set; }
        public string content { get; set; }
    }
}
