//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrders
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrdersEntities : DbContext
    {
        public OrdersEntities()
            : base("name=OrdersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agents> agents1 { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GoodsAgent> GoodsAgents { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PriceCustomer> PriceCustomers { get; set; }
        public virtual DbSet<PriceDiscount> PriceDiscounts { get; set; }
        public virtual DbSet<PriceRef> PriceRefs { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<logsString> logsStrings { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<balance> balances { get; set; }
        public virtual DbSet<history> histories { get; set; }
    }
}
