//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceCustomer
    {
        public int id { get; set; }
        public string wareId { get; set; }
        public string kntrId { get; set; }
        public string namePrice { get; set; }
        public int idObj { get; set; }
        public string objid { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
