//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class superdebts
    {
        public int id { get; set; }
        public System.DateTime period { get; set; }
        public string super { get; set; }
        public double bal { get; set; }
        public double debt { get; set; }
        public double lastBal { get; set; }
        public double lastDebt { get; set; }
        public int count { get; set; }
        public int countLast { get; set; }
    }
}
